import { WasteCategoryInfo, WasteCategory } from '@/types/waste';

export const WASTE_CATEGORIES: Record<WasteCategory, WasteCategoryInfo> = {
  organic: {
    id: 'organic',
    name: 'Organic & Food Waste',
    tagline: 'Compostable kitchen scraps, vegetable peels, lawn trimmings',
    color: 'emerald',
    accentBg: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-400',
    borderColor: 'border-emerald-500/30 hover:border-emerald-500',
    iconName: 'Apple',
    examples: ['Food leftovers', 'Fruit & veggie peels', 'Coffee grounds', 'Garden trimmings', 'Eggshells'],
    co2Factor: 1.25,
    ecoPointsPerKg: 10,
    recyclingInstructions: 'Keep in a sealed compost bag. Avoid plastic wrapping or non-biodegradable tape.',
  },
  plastic: {
    id: 'plastic',
    name: 'Dry Recyclable Plastics',
    tagline: 'Water bottles, milk jugs, detergent containers, clean packaging',
    color: 'blue',
    accentBg: 'bg-blue-50 text-blue-700 dark:bg-blue-950/40 dark:text-blue-400',
    borderColor: 'border-blue-500/30 hover:border-blue-500',
    iconName: 'Package',
    examples: ['PET water bottles', 'HDPE containers', 'Clean plastic wraps', 'Takeaway containers'],
    co2Factor: 1.8,
    ecoPointsPerKg: 15,
    recyclingInstructions: 'Rinse out liquids, dry completely, and flatten or crush to optimize collection volume.',
  },
  ewaste: {
    id: 'ewaste',
    name: 'Electronic Waste (E-Waste)',
    tagline: 'Phones, cables, laptops, circuit boards, appliances',
    color: 'amber',
    accentBg: 'bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-400',
    borderColor: 'border-amber-500/30 hover:border-amber-500',
    iconName: 'Cpu',
    examples: ['Old laptops & phones', 'Chargers & cables', 'PCBs & hard drives', 'Dry cell batteries', 'Monitors'],
    co2Factor: 3.5,
    ecoPointsPerKg: 40,
    recyclingInstructions: 'Remove lithium batteries if possible. Secure data devices. Hand over directly to certified handlers.',
  },
  hazardous: {
    id: 'hazardous',
    name: 'Hazardous & Medical Waste',
    tagline: 'Chemicals, paint cans, fluorescent tubes, discarded medicine',
    color: 'rose',
    accentBg: 'bg-rose-50 text-rose-700 dark:bg-rose-950/40 dark:text-rose-400',
    borderColor: 'border-rose-500/30 hover:border-rose-500',
    iconName: 'AlertTriangle',
    examples: ['Paints & thinners', 'Aerosol cans', 'Expired medicines', 'Sanitary & medical swabs', 'Pesticides'],
    co2Factor: 2.1,
    ecoPointsPerKg: 25,
    recyclingInstructions: 'Must be in leak-proof, marked containers. Never mix different chemical solutions.',
  },
  paper: {
    id: 'paper',
    name: 'Paper & Cardboard',
    tagline: 'Corrugated cartons, newspapers, cartons, office paper',
    color: 'amber',
    accentBg: 'bg-amber-50 text-amber-800 dark:bg-amber-950/30 dark:text-amber-300',
    borderColor: 'border-amber-600/30 hover:border-amber-600',
    iconName: 'FileText',
    examples: ['Delivery cardboard boxes', 'Newspapers & magazines', 'Exam notes & office paper', 'Carton packaging'],
    co2Factor: 1.5,
    ecoPointsPerKg: 12,
    recyclingInstructions: 'Flatten all boxes. Must be dry and free of greasy oil stains or food residue.',
  },
  metal: {
    id: 'metal',
    name: 'Metal & Scrap Appliances',
    tagline: 'Beverage cans, steel cutlery, copper wires, metal junk',
    color: 'indigo',
    accentBg: 'bg-indigo-50 text-indigo-700 dark:bg-indigo-950/40 dark:text-indigo-400',
    borderColor: 'border-indigo-500/30 hover:border-indigo-500',
    iconName: 'Wrench',
    examples: ['Aluminium soda cans', 'Steel scrap', 'Copper wiring', 'Old cooking pans', 'Bicycle parts'],
    co2Factor: 4.2,
    ecoPointsPerKg: 35,
    recyclingInstructions: 'Empty and crush cans. Bundle loose wires together with paper ties.',
  },
};

export const PUNE_ZONES = [
  'Flora Institute of Technology Campus',
  'Hadapsar & Magarpatta',
  'Kharadi IT Park',
  'Viman Nagar',
  'Kothrud',
  'Hinjawadi Infotech Phase 1-3',
  'Baner - Balewadi',
  'Shivajinagar / Camp',
];

export const TIME_SLOTS = [
  '08:30 AM - 11:30 AM (Morning Slot)',
  '12:00 PM - 03:00 PM (Midday Slot)',
  '03:30 PM - 06:30 PM (Evening Slot)',
  '07:00 PM - 09:00 PM (Express Green Slot)',
];
